#include "constants-formats.h"

#ifndef FACILITIES_H
#define FACILITIES_H

/*** CURRENT APPLICATION STATE DESCRIPTION ***/

#define FACILITIES_MODE_STORE_MANIPULATION 0
#define FACILITIES_MODE_PASSWORD_MANIPULATION 1
#define FACILITIES_MODE_MEMORIZATION 2
#define FACILITIES_MODE_TRANSFER 3

static unsigned short mode = FACILITIES_MODE_STORE_MANIPULATION;

static char *field_name = NULL;

static Store* loaded_store = NULL;
static char* loaded_store_path = NULL;

static char* password_format = FORMAT_AZaz09;
static unsigned int password_length = 20;

// State variable
static unsigned long facilities_state = 0;

// Flags
#define FACILITIES_FLAG_STORE_LOADED			(0b1 << 0)
#define FACILITIES_FLAG_KEY_INSERTED			(0b1 << 1)
#define FACILITIES_FLAG_STORE_DIRTY				(0b1 << 2)
#define FACILITIES_FLAG_STORE_INIT_COMPLETE		(0b1 << 3)
#define FACILITIES_FLAG_STORE_UNLOCKED			(0b1 << 4)

// Getters
#define FACILITIES_STORE_LOADED				(facilities_state & FACILITIES_FLAG_STORE_LOADED)
#define FACILITIES_KEY_INSERTED				(facilities_state & FACILITIES_FLAG_KEY_INSERTED)
#define FACILITIES_STORE_DIRTY				(facilities_state & FACILITIES_FLAG_STORE_DIRTY)
#define FACILITIES_STORE_INIT_COMPLETE		(facilities_state & FACILITIES_FLAG_STORE_INIT_COMPLETE)
#define FACILITIES_STORE_UNLOCKED			(facilities_state & FACILITIES_FLAG_STORE_UNLOCKED)

// Setters
#define FACILITIES_SET_STORE_LOADED(VALUE)	 		facilities_state = facilities_state - FACILITIES_STORE_LOADED + FACILITIES_FLAG_STORE_LOADED * VALUE
#define FACILITIES_SET_KEY_INSERTED(VALUE)	 		facilities_state = facilities_state - FACILITIES_KEY_INSERTED + FACILITIES_FLAG_KEY_INSERTED * VALUE
#define FACILITIES_SET_STORE_DIRTY(VALUE)	 		facilities_state = facilities_state - FACILITIES_STORE_DIRTY + FACILITIES_FLAG_STORE_DIRTY * VALUE
#define FACILITIES_SET_STORE_INIT_COMPLETE(VALUE)	facilities_state = facilities_state - FACILITIES_STORE_INIT_COMPLETE + FACILITIES_FLAG_STORE_INIT_COMPLETE * VALUE
#define FACILITIES_SET_STORE_UNLOCKED(VALUE)		facilities_state = facilities_state - FACILITIES_STORE_UNLOCKED + FACILITIES_FLAG_STORE_UNLOCKED * VALUE

/*** FACILITIES ***/

#define FACILITIES_OK 			0
#define FACILITIES_WRONG_MODE	1000

#define FACILITIES_SWITCH_MODE_UNKNOWN_MODE		1

int facility_switch_mode(unsigned short new_mode);

#define FACILITIES_SET_WRONG_FIELD_NAME_FOR_MODE	2

int facility_set(char* field_name);

#define FACILITIES_GET_WRONG_FIELD_NAME_FOR_MODE				3
#define FACILITIES_GET_NOT_IMPLEMENTED							4
#define FACILITIES_GET_STORE_MANIPULATION_STORE_NOT_LOADED		5

int facility_get(char* field_name_to_get);

#define FACILITIES_TO_STORE_MANIPULATION_STORE_NOT_LOADED		6
#define FACILITIES_TO_STORE_MANIPULATION_KEY_NOT_VERIFIABLE		7
#define FACILITIES_TO_STORE_MANIPULATION_ALGORITHM_UNSUPPORTED	8
#define FACILITIES_TO_PASSWORD_MANIPULATION_INVALID_LENGTH		9
#define FACILITIES_TO_PASSWORD_MANIPULATION_INVALID_FORMAT		10
#define	FACILITIES_TO_NOT_IMPLEMENTED							11

int facility_to(char* field_value);

#define FACILITIES_INIT_STORE_ALREADY_LOADED	12

int facility_init();

#define FACILITIES_LOAD_STORE_ALREADY_LOADED	13
#define FACILITIES_LOAD_FILE_ERROR				-1
#define FACILITIES_LOAD_DESERIALIZE_ERROR		-2

int facility_load(char* path);

#define FACILITIES_UNLOCK_STORE_NOT_LOADED					14
#define FACILITIES_UNLOCK_STORE_INIT_NOT_COMPLETE			15
#define FACILITIES_UNLOCK_UNABLE_TO_GENERATE_SHUFFLE_KEY	16
#define FACILITIES_UNLOCK_UNKNOWN_ERROR						17
#define FACILITIES_UNLOCK_KEY_EXISTS_NOT_REPLACING			18
#define FACILITIES_UNLOCK_VERIFICATION_FAILED				19
#define FACILITIES_UNLOCK_NO_KEY_PROVIDED					20
#define FACILITIES_UNLOCK_STORE_ALREADY_UNLOCKED			21

int facility_unlock();

#define FACILITIES_LOCK_STORE_NOT_LOADED			22
#define FACILITIES_LOCK_STORE_INIT_NOT_COMPLETE		23
#define FACILITIES_LOCK_STORE_ALREADY_LOCKED		24

int facility_lock();

#define FACILITIES_SAVE_STORE_INIT_NOT_COMPLETE		25
#define FACILITIES_SAVE_NO_PATH_PROVIDED			26
#define FACILITIES_SAVE_NOTHING_TO_SAVE				27
#define FACILITIES_SAVE_STORE_NOT_LOADED			28
#define FACILITIES_SAVE_FILE_ERROR					-3
#define FACILITIES_SAVE_OVERWRITE_DENIED			-4
#define FACILITIES_SAVE_SERIALIZE_ERROR				-5

int facility_save();

int facility_save_as(char* path);

#define FACILITIES_CLOSE_STORE_NOT_LOADED		29
#define FACILITIES_CLOSE_DIRTY_DISCARD_DENIED	30

int facility_close();

#define FACILITIES_FETCH_STORE_NOT_LOADED			31
#define FACILITIES_FETCH_STORE_INIT_NOT_COMPLETE	32
#define FACILITIES_FETCH_STORE_LOCKED				33
#define FACILITIES_FETCH_ID_OUT_OF_BOUNDS			34
#define FACILITIES_FETCH_PASSWORD_ENTRY_IS_NULL		35
#define FACILITIES_FETCH_PASSWORD_STRING_IS_NULL	36
#define FACILITIES_FETCH_PRINT_FAILED				37

int facility_fetch(unsigned long id);

#define FACILITIES_FIND_STORE_NOT_LOADED			38
#define FACILITIES_FIND_STORE_INIT_NOT_COMPLETE		39
#define FACILITIES_FIND_NO_PASSWORDS_FOUND			40

int facility_find(char* identifier);

#define FACILITIES_GENERATE_STORE_NOT_LOADED			41
#define FACILITIES_GENERATE_STORE_INIT_NOT_COMPLETE		42
#define FACILITIES_GENERATE_STORE_LOCKED				43

int facility_generate(char* identifier);

#define FACILITIES_REMOVE_STORE_NOT_LOADED			44
#define FACILITIES_REMOVE_STORE_INIT_NOT_COMPLETE	45
#define FACILITIES_REMOVE_REMOVED_PASSWORD_IS_NULL	46

int facility_remove(unsigned long id);

int facility_memorize(unsigned long id);

int facility_send();

int facility_receive();

#endif